version: "3.1"
services:
    www:
        build: .
        container_name: Debian
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            - ./etc/apache2/apache2.conf:/etc/apache2/apache2.conf
            - ./etc/php/8.1/apache2/php.ini:/etc/php/8.1/apache2/php.ini
        links:
            - db
 
        command: tail -f /dev/null      
    
    db:
        image: mysql:8.0
        container_name: db_Video
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: video
            MYSQL_USER: andres
            MYSQL_PASSWORD: Kb.204.2022
            MYSQL_ROOT_PASSWORD: Kb.204.2022 
        volumes:
            - ./www/model:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: Phpmyadmi_video
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: andres
            MYSQL_PASSWORD:  Kb.204.2022
            MYSQL_ROOT_PASSWORD:  Kb.204.2022 